spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
rsa:
  key:
    public: classpath:public.key
    private: classpath:private.key
